### ISSUE TITLE
Filters extremly slow on mobile safari

### ISSUE THREAD

**Issue by emile818** [alexmic/filtrr#1]
Hello, first good work on the filter working great on pc (mac i7 ). However i tried on mobile safari 3g and inside phonegap webkit application and it is super slow, i tried these filteres http://www.html5rocks.com/en/tutorials/canvas/imagefilters/ and they are working fine on mobile.
I added a comment on quora about the filters processing being so slow.

**Comment by alexmic** [comment]
Hi, to be honest I never tested the filters on a mobile phone. It's not meant to be a production ready library, it was just a weekend hack! :-) I am afraid I don't have the time now to look into it (uni work), but you are free to fork it and make any changes you like!

**Comment by alexmic** [comment]
Also, I don't see major differences in the way I process the pixels with the library you provided. Maybe it's just a bug with the rest of the code? How long did it take on your phone?

**Comment by emile818** [comment]
it takes arround 15 second or more on an iphone 3gs, i will be free next week i will give it a shot and see what's going on. I believe the processor of the mobile is too small for image processing inside a canvas,
Good luck with uni

**Comment by emile818** [comment]
Here is a time log for e1:

2011-06-16 15:49:45.183 Signal[1417:307] [INFO] calling filter e1 1308228528524
2011-06-16 15:49:45.211 Signal[1417:307] [INFO] filtrr.img 1308228528916
2011-06-16 15:49:45.240 Signal[1417:307] [INFO] filtr.duplicate 1308228528916
2011-06-16 15:49:45.269 Signal[1417:307] [INFO] topFiltr.core.saturation 1308228529034
2011-06-16 15:49:45.297 Signal[1417:307] [INFO] filtr.blend.multiply 1308228553638
2011-06-16 15:49:45.325 Signal[1417:307] [INFO] filtr.core.tint 1308228562861
2011-06-16 15:49:45.352 Signal[1417:307] [INFO] filtr.put 1308228584750
2011-06-16 15:49:45.381 Signal[1417:307] [INFO] filtr.canvas().getContext 1308228584767

**Comment by emile818** [comment]
readable log:

start Thu Jun 16 2011 16:06:37
filtrr.img Thu Jun 16 2011 16:06:38
filtr.duplicate Thu Jun 16 2011 16:06:38
topFiltr.core.saturation Thu Jun 16 2011 16:06:38
filtr.blend.multiply Thu Jun 16 2011 16:07:14
filtr.core.tint Thu Jun 16 2011 16:07:26
filtr.put Thu Jun 16 2011 16:07:58
filtr.canvas().getContext Thu Jun 16 2011 16:07:58
End Thu Jun 16 2011 16:07:58

**Comment by alexmic** [comment]
Jesus, that's too slow! Thanks for the logs - I'll take a look when I have time!

**Comment by RS303** [comment]
Just wondering has this issue been fixed to run faster on a mobile device?

**Comment by alexmic** [comment]
No work has been done on performance yet sorry :/

**Comment by RS303** [comment]
Thanks Alex,
Can you send me the picture frame? I did not see it in the code, I must have missed it. 

thanks so much for your help.
Russell

--- On Sun, 3/18/12, Alex Michael reply@reply.github.com wrote:

**Comment by alexmic** [comment]
Hey Russel - here's a link: http://alexmic.github.com/filtrr/whiteframe.png

**Comment by RS303** [comment]
Thank you so much. Let me know when the new version comes out or any of the other filters!

Russell 

--- On Tue, 3/20/12, Alex Michael reply@reply.github.com wrote:
