### ISSUE TITLE
Resetting of Filtrr

### ISSUE THREAD

**Issue by iandevlin** [alexmic/filtrr#15]
There doesn't seem to be a way to reset the Filtrr2 object once you have applied an effect to it. Trying to recreate a new Filtrr2 object on the same canvas element doesn't work either so if I apply a brighten(50) effect on a canvas and want to then apply a sepia() effect on the same canvas but from the original image and not the current image, it doesn't work.

Redrawring the original image to the canvas and then applying the new effect doesn't work either.

Any chance of adding a reset() function that would clear all effects?

**Comment by alexmic** [comment]
Hey Ian, thanks for this. I will work on it soon.

**Comment by alexmic** [comment]
Hey @iandevlin, I just pushed 0.5 which contains a `reset()` method. Does that work for you? I updated the readme documentation and created an example as well.

**Comment by iandevlin** [comment]
Hi Alec, fast response! Many thanks for that! I won't be able to try it for a bit, but if you've tested it I suspect it works :-) I'll let you know of course. Thanks again.

**Comment by iandevlin** [comment]
Hi Alec! Just had a chance to test it, works like a charm. Many thanks!

**Comment by iandevlin** [comment]
Hmm, I spoke too soon. If I change the image in the canvas dynamically, the image in the filtrr2 still remains as the previous image.

**Comment by alexmic** [comment]
What do you mean dynamically? Can you give me some example code?

**Comment by iandevlin** [comment]
Sorry, I should have been clear. I mean if I draw something to the canvas and apply a filter - all is well. If, while the same image is in the canvas and I apply a new filter (calling reset() beforehand) all works well.

But if I change the image in the canvas, call reset() and apply a filter, the filter is applied to the previous image that was in the canvas and not the new one.

**Comment by alexmic** [comment]
Hm, so this is happening because each Filtrr2 object is designed to work with the image that it is applied on. Internally it stores the canvas image data and writes it back on `render()`. When you change the image, the image data do not change hence you get the old image. `reset()` just sets the image data to a "clean" copy of the original image. The Filtrr2 constructor also caches instances and returns the same one for the same selector.

**Comment by iandevlin** [comment]
Yeah, I understand why it's happening but it's not what I need I'm afraid. Any chance of adding a boolean to the reset() function, which when true, also clears the image cache? Default would of course be false.

**Comment by alexmic** [comment]
Yeah that's not a bad idea - either that or add a new method `reinit()` or something so that it's more explicit. I will work on it as soon as I find some free time.

**Comment by iandevlin** [comment]
Sounds like a plan, and thanks again for the speedy feedback.

**Comment by alexmic** [comment]
Hey @iandevlin, 

Sorry for taking ages to fix this. 

I've just pushed a fix that allows options to be passed in the constructor. The only option available for now is 'store'. Setting it to false will allow you to create new Filtrr2 instances on the same elements, hence once you change the canvas image you can actually create a new instance to override your previous one. Remember to use store=false for all your instances if this is a comming occurence, for example:

```
var f = Filtrr2("#id", function() {..}, {
    store: false
 });
```
