### ISSUE TITLE
Saving the canvas as an image

### ISSUE THREAD

**Issue by parth16** [alexmic/filtrr#2]
Great job on the filters!

Is there a way to convert the newly created canvas back to an image? I would like to save the image after its filtered. Is there a way to do that?

**Comment by alexmic** [comment]
Hey,

Yes you can do that! The filtr object gives you access to the canvas element through the canvas() method. You can then do this (on click for example): window.open(filtr.canvas().toDataURL(), "w"); 

This will popup a new window with the image in it and you can then right click save-as. You can also insert an img tag into your document: 
  var newImg = document.createElement("img");
  newImg.src = filtr.canvas().toDataURL();
  document.body.appendChild(newImg);

}

**Comment by parth16** [comment]
Thanks for the reply. This worked for me. I am trying to post the newly created image to Facebook using the Graph API. However, it's tricky as there's no file name or file path. Have you tried it out? 

Thanks!

**Comment by alexmic** [comment]
If you put the output of toDataURL() as the src of an <img> tag it will show the image.

**Comment by parth16** [comment]
I found an issue where if you specify a image URL in the bigpic src attribute, then filtrr algo just hangs.

For the same photo, saved locally on my filesystem, the algorithm does work.

Have you tried this yourself?

**Comment by alexmic** [comment]
I tried it, it doesn't work because of a JavaScript security exception. More here: http://stackoverflow.com/questions/2704929/uncaught-error-security-err-dom-exception-18.
