### ISSUE TITLE
Website filtrr.me not working

### ISSUE THREAD

**Issue by wamatt** [alexmic/filtrr#20]
First one is greeted with this:

![Ooops](http://i.imgur.com/70uxf.png)

Followed by a 404.

**Comment by alexmic** [comment]
Hey, I am aware of this issue. Until this is fixed, you can access the website here: http://alexmic.github.com/filtrr/

**Comment by alexmic** [comment]
This is fixed now.

**Comment by wamatt** [comment]
Cool :)
